<?php
/**
 * Block Patterns for Survey Form Block.
 *
 * Registers ready-to-use production survey templates directly in Gutenberg
 * under the "Survey Forms" category.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

if ( ! class_exists( 'BPSVB_Patterns' ) ) {
    class BPSVB_Patterns {

        const CATEGORY_SLUG = 'survey-form-block';

        public function __construct() {
            add_action( 'init', [ $this, 'registerPatterns' ] );
        }

        /**
         * Registers pattern category and block patterns.
         *
         * @return void
         */
        public function registerPatterns() {
            if ( ! function_exists( 'register_block_pattern_category' ) || ! function_exists( 'register_block_pattern' ) ) {
                return;
            }

            register_block_pattern_category(
                self::CATEGORY_SLUG,
                [
                    'label' => __( 'Survey Forms', 'survey-form-block' ),
                ]
            );

            $patterns = self::getPatternsData();

            foreach ( $patterns as $name => $pattern ) {
                register_block_pattern(
                    'survey-form-block/' . $name,
                    [
                        'title'         => $pattern['title'],
                        'description'   => $pattern['description'],
                        'categories'    => [ self::CATEGORY_SLUG ],
                        'keywords'      => $pattern['keywords'],
                        'viewportWidth' => 800,
                        'content'       => $pattern['content'],
                    ]
                );
            }
        }

        /**
         * Returns block pattern definitions for the 6 real-world use cases.
         *
         * @return array
         */
        public static function getPatternsData() {
            return [
                'csat-nps' => [
                    'title'       => __( 'Customer Satisfaction & NPS (CSAT / NPS)', 'survey-form-block' ),
                    'description' => __( 'Measure customer satisfaction and Net Promoter Score with 5-star ratings, NPS 0-10 scale, multi-select tags, and follow-up toggle.', 'survey-form-block' ),
                    'keywords'    => [ 'survey', 'csat', 'nps', 'feedback', 'customer', 'rating' ],
                    'content'     => self::getBlockContent( 'csat-nps' ),
                ],
                'product-feedback' => [
                    'title'       => __( 'Product Feedback & Feature Request', 'survey-form-block' ),
                    'description' => __( 'Collect product feedback and feature requests with 1-10 opinion scales, friction range sliders, and beta testing enrollment.', 'survey-form-block' ),
                    'keywords'    => [ 'survey', 'product', 'feedback', 'roadmap', 'feature', 'saas' ],
                    'content'     => self::getBlockContent( 'product-feedback' ),
                ],
                'event-registration' => [
                    'title'       => __( 'Event Registration & Attendee Preferences', 'survey-form-block' ),
                    'description' => __( 'Conference and webinar registration form featuring attendee details, session checkboxes, dietary select, and arrival date.', 'survey-form-block' ),
                    'keywords'    => [ 'survey', 'event', 'registration', 'conference', 'webinar', 'tickets' ],
                    'content'     => self::getBlockContent( 'event-registration' ),
                ],
                'job-application' => [
                    'title'       => __( 'Job Application & Candidate Screening', 'survey-form-block' ),
                    'description' => __( 'Candidate screening application form with portfolio URL, years experience, technical proficiency scale, and work authorization.', 'survey-form-block' ),
                    'keywords'    => [ 'survey', 'career', 'job', 'application', 'hiring', 'recruiting' ],
                    'content'     => self::getBlockContent( 'job-application' ),
                ],
                'bug-report' => [
                    'title'       => __( 'Website Usability & Bug Report Form', 'survey-form-block' ),
                    'description' => __( 'Bug tracker and issue report form with affected URL, severity radio, issue category, date picker, and steps to reproduce.', 'survey-form-block' ),
                    'keywords'    => [ 'survey', 'bug', 'report', 'issue', 'ticket', 'support' ],
                    'content'     => self::getBlockContent( 'bug-report' ),
                ],
                'employee-onboarding' => [
                    'title'       => __( 'Employee Onboarding & 30-Day Check-in', 'survey-form-block' ),
                    'description' => __( 'Pulse survey for new hires to assess first-month support, tooling access, role clarity, and mentorship feedback.', 'survey-form-block' ),
                    'keywords'    => [ 'survey', 'employee', 'onboarding', 'hr', 'pulse', 'internal' ],
                    'content'     => self::getBlockContent( 'employee-onboarding' ),
                ],
            ];
        }

        /**
         * Helper returning block content string for a given template key.
         *
         * @param string $key
         * @return string
         */
        public static function getBlockContent( $key ) {
            $data = self::getTemplateAttributes( $key );
            if ( ! $data ) {
                return '';
            }
            return '<!-- wp:svb/survey-block ' . wp_json_encode( $data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE ) . ' /-->';
        }

        /**
         * Returns survey block attributes matching the production-ready use cases.
         *
         * @param string $key
         * @return array
         */
        public static function getTemplateAttributes( $key ) {
            switch ( $key ) {
                case 'csat-nps':
                    return [
                        'cId' => 'svb-csat-nps',
                        'form' => [
                            'id' => 'svb-form-csat-nps',
                            'creator_id' => 1,
                            'title' => 'Customer Satisfaction & NPS Survey',
                            'description' => 'Help us improve your experience by sharing quick feedback on your recent interaction.',
                            'bgColor' => '#ffffff',
                            'padding' => [ 'top' => '32px', 'right' => '32px', 'bottom' => '32px', 'left' => '32px' ],
                            'border' => [ 'width' => '1px', 'style' => 'solid', 'color' => '#e2e8f0', 'side' => 'all', 'radius' => '12px' ],
                            'titleColor' => '#0f172a',
                            'titleAlign' => 'left',
                            'titleTypo' => [ 'fontSize' => [ 'desktop' => 22, 'tablet' => 20, 'mobile' => 18 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'titleMargin' => [ 'top' => '0px', 'right' => '0px', 'bottom' => '8px', 'left' => '0px' ],
                            'descriptionColor' => '#64748b',
                            'descriptionAlign' => 'left',
                            'descriptionTypo' => [ 'fontSize' => [ 'desktop' => 15, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 400, 'lineHeight' => '145%' ],
                            'descriptionMargin' => [ 'top' => '0px', 'right' => '0px', 'bottom' => '24px', 'left' => '0px' ],
                            'successMsg' => 'Thank you! Your feedback helps us make our service better for everyone.',
                            'successMsgColor' => '#16a34a'
                        ],
                        'fields' => [
                            [
                                'id' => 'cs_name',
                                'type' => 'text',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Full Name',
                                'labelPosition' => 'column',
                                'help' => '',
                                'placeholder' => 'e.g. Alex Morgan',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'cs_email',
                                'type' => 'email',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Business Email',
                                'labelPosition' => 'column',
                                'help' => '',
                                'placeholder' => 'alex@company.com',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'cs_duration',
                                'type' => 'select',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'How long have you been using our platform?',
                                'labelPosition' => 'column',
                                'help' => '',
                                'placeholder' => 'Select account duration',
                                'isRequired' => false,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'Less than 1 month', 'value' => '<1m' ],
                                    [ 'label' => '1 to 6 months', 'value' => '1-6m' ],
                                    [ 'label' => '6 to 12 months', 'value' => '6-12m' ],
                                    [ 'label' => 'Over 1 year', 'value' => '>1y' ],
                                ],
                            ],
                            [
                                'id' => 'cs_rating',
                                'type' => 'star_rating',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Overall Satisfaction with our Service',
                                'labelPosition' => 'column',
                                'help' => 'Rate your overall experience from 1 to 5 stars',
                                'isRequired' => true,
                                'isDisable' => false,
                                'maxStars' => 5,
                            ],
                            [
                                'id' => 'cs_nps',
                                'type' => 'nps',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'How likely are you to recommend us to a colleague or friend?',
                                'labelPosition' => 'column',
                                'help' => '0 = Not at all likely, 10 = Extremely likely',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'cs_features',
                                'type' => 'checkbox',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Which core features do you use most frequently?',
                                'labelPosition' => 'column',
                                'help' => 'Select all that apply to your daily workflow',
                                'isRequired' => false,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'Real-Time Analytics & Dashboards', 'value' => 'analytics' ],
                                    [ 'label' => 'Automated Workflow Pipelines', 'value' => 'workflows' ],
                                    [ 'label' => 'Team Collaboration & Comments', 'value' => 'collaboration' ],
                                    [ 'label' => 'API & Webhook Integrations', 'value' => 'api' ],
                                    [ 'label' => 'Mobile Access & Alerts', 'value' => 'mobile' ],
                                ],
                            ],
                            [
                                'id' => 'cs_improve',
                                'type' => 'paragraph',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'What is the single most important improvement we could make?',
                                'labelPosition' => 'column',
                                'help' => 'Tell us what would make your experience 10x better',
                                'placeholder' => 'Share your candid feedback or ideas...',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'cs_followup',
                                'type' => 'toggle',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'May our Customer Success team contact you for follow-up questions?',
                                'labelPosition' => 'column',
                                'help' => '',
                                'onLabel' => 'Yes, happy to chat',
                                'offLabel' => 'No, thank you',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                        ],
                        'labelS' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 15, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'color' => '#0f172a',
                        ],
                        'input' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 14, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 400, 'lineHeight' => '135%' ],
                            'color' => '#0f172a',
                            'padding' => [ 'top' => '11px', 'right' => '14px', 'bottom' => '11px', 'left' => '14px' ],
                            'border' => [ 'width' => '1px', 'style' => 'solid', 'color' => '#e2e8f0', 'side' => 'all', 'radius' => '8px' ],
                        ],
                        'radioCheckLabelColor' => '#334155',
                        'button' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 16, 'tablet' => 15, 'mobile' => 14 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'colors' => [ 'color' => '#ffffff', 'bg' => '#2563eb' ],
                            'padding' => [ 'top' => '14px', 'right' => '28px', 'bottom' => '14px', 'left' => '28px' ],
                        ],
                        'design' => [
                            'theme' => 'modern-minimal',
                            'layout' => 'minimal',
                            'inputStyle' => 'outlined',
                            'button' => [
                                'variant' => 'filled',
                                'label' => 'Submit Feedback',
                                'width' => 'full',
                                'align' => 'left',
                                'radius' => '8px',
                                'hoverEffect' => 'none',
                                'transition' => 250,
                            ],
                            'card' => [ 'enable' => false ],
                            'progress' => [
                                'enable' => true,
                                'style' => 'gradient',
                                'position' => 'top',
                                'height' => '6px',
                                'gradient' => 'linear-gradient(135deg, #2563eb 0%, #38bdf8 100%)',
                                'showLabel' => true,
                            ],
                            'success' => [
                                'style' => 'card',
                                'icon' => 'check',
                                'animation' => 'fade',
                                'title' => 'Feedback Received!',
                                'duration' => 3000,
                            ],
                            'label' => [ 'requiredMark' => 'badge' ],
                        ],
                    ];

                case 'product-feedback':
                    return [
                        'cId' => 'svb-product-fb',
                        'form' => [
                            'id' => 'svb-form-product-fb',
                            'creator_id' => 1,
                            'title' => 'Product Feedback & Feature Request',
                            'description' => 'Tell us what you love and what features you would like to see on our product roadmap.',
                            'bgColor' => '#f8fafc',
                            'padding' => [ 'top' => '30px', 'right' => '28px', 'bottom' => '30px', 'left' => '28px' ],
                            'border' => [ 'width' => '0px', 'style' => 'solid', 'color' => '#e9ecf5', 'side' => 'all', 'radius' => '18px' ],
                            'titleColor' => '#1e293b',
                            'titleAlign' => 'left',
                            'titleTypo' => [ 'fontSize' => [ 'desktop' => 22, 'tablet' => 20, 'mobile' => 18 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'titleMargin' => [ 'top' => '0px', 'right' => '0px', 'bottom' => '8px', 'left' => '0px' ],
                            'descriptionColor' => '#64748b',
                            'descriptionAlign' => 'left',
                            'descriptionTypo' => [ 'fontSize' => [ 'desktop' => 15, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 400, 'lineHeight' => '145%' ],
                            'descriptionMargin' => [ 'top' => '0px', 'right' => '0px', 'bottom' => '24px', 'left' => '0px' ],
                            'successMsg' => 'Thank you! Your suggestion has been logged directly into our Product Roadmap queue.',
                            'successMsgColor' => '#0f9d58'
                        ],
                        'fields' => [
                            [
                                'id' => 'pf_name',
                                'type' => 'text',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Your Name',
                                'labelPosition' => 'column',
                                'placeholder' => 'e.g. Jordan Lee',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'pf_email',
                                'type' => 'email',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Account Email',
                                'labelPosition' => 'column',
                                'placeholder' => 'jordan@example.com',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'pf_platform',
                                'type' => 'radio',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Which environment do you primarily use?',
                                'labelPosition' => 'column',
                                'isRequired' => true,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'Web App (Chrome / Firefox / Safari)', 'value' => 'web' ],
                                    [ 'label' => 'Desktop App (macOS)', 'value' => 'macos' ],
                                    [ 'label' => 'Desktop App (Windows)', 'value' => 'windows' ],
                                    [ 'label' => 'Mobile App (iOS / Android)', 'value' => 'mobile' ],
                                ],
                            ],
                            [
                                'id' => 'pf_ease',
                                'type' => 'opinion_scale',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'How intuitive is our user interface?',
                                'labelPosition' => 'column',
                                'help' => '1 = Extremely Complex, 10 = Completely Intuitive',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'pf_feature',
                                'type' => 'select',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Which upcoming feature would add the greatest value?',
                                'labelPosition' => 'column',
                                'placeholder' => 'Select a requested feature',
                                'isRequired' => false,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'AI Assistant for Automated Summaries', 'value' => 'ai_assistant' ],
                                    [ 'label' => 'Native Zapier & Make.com Integrations', 'value' => 'zapier' ],
                                    [ 'label' => 'Granular Role-Based Permissions (RBAC)', 'value' => 'rbac' ],
                                    [ 'label' => 'Custom Webhooks & REST API Access', 'value' => 'webhooks' ],
                                    [ 'label' => 'Offline Storage & Auto-Sync', 'value' => 'offline' ],
                                ],
                            ],
                            [
                                'id' => 'pf_friction',
                                'type' => 'range_slider',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'How often do you encounter workflow friction or blockers?',
                                'labelPosition' => 'column',
                                'help' => 'Slide from 1 (Never) to 10 (Daily)',
                                'min' => 1,
                                'max' => 10,
                                'step' => 1,
                                'value' => 3,
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'pf_details',
                                'type' => 'paragraph',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Describe your feature request or current pain points in detail',
                                'labelPosition' => 'column',
                                'help' => 'Include use case context, expected output, or what problem it solves',
                                'placeholder' => 'We would love to have...',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'pf_beta',
                                'type' => 'toggle',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Would you like early access to our private Beta testing program?',
                                'labelPosition' => 'column',
                                'onLabel' => 'Count me in!',
                                'offLabel' => 'Not right now',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                        ],
                        'labelS' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 15, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'color' => '#1e293b',
                        ],
                        'input' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 14, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 400, 'lineHeight' => '135%' ],
                            'color' => '#1e293b',
                            'padding' => [ 'top' => '11px', 'right' => '14px', 'bottom' => '11px', 'left' => '14px' ],
                            'border' => [ 'width' => '1px', 'style' => 'solid', 'color' => '#e4e8f2', 'side' => 'all', 'radius' => '10px' ],
                        ],
                        'radioCheckLabelColor' => '#475569',
                        'button' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 16, 'tablet' => 15, 'mobile' => 14 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'colors' => [ 'color' => '#ffffff', 'bg' => '#6366f1' ],
                            'padding' => [ 'top' => '14px', 'right' => '28px', 'bottom' => '14px', 'left' => '28px' ],
                        ],
                        'design' => [
                            'theme' => 'soft-card',
                            'layout' => 'card',
                            'inputStyle' => 'outlined',
                            'card' => [
                                'enable' => true,
                                'radius' => '14px',
                                'hoverEffect' => 'lift',
                            ],
                            'button' => [
                                'variant' => 'filled',
                                'label' => 'Send Product Feedback',
                                'width' => 'full',
                                'align' => 'left',
                                'radius' => '10px',
                                'hoverEffect' => 'lift',
                                'transition' => 250,
                            ],
                            'progress' => [
                                'enable' => true,
                                'style' => 'linear',
                                'position' => 'top',
                                'height' => '6px',
                                'showLabel' => true,
                            ],
                            'success' => [
                                'style' => 'card',
                                'icon' => 'check',
                                'animation' => 'fade',
                                'title' => 'Thank You!',
                                'duration' => 3000,
                            ],
                            'label' => [ 'requiredMark' => 'badge' ],
                        ],
                    ];

                case 'event-registration':
                    return [
                        'cId' => 'svb-event-reg',
                        'form' => [
                            'id' => 'svb-form-event-reg',
                            'creator_id' => 1,
                            'title' => 'Global Tech Summit 2026 Registration',
                            'description' => 'Join 2,500+ engineers, product managers, and founders in San Francisco or virtually worldwide.',
                            'bgColor' => '#ffffff',
                            'padding' => [ 'top' => '32px', 'right' => '32px', 'bottom' => '32px', 'left' => '32px' ],
                            'border' => [ 'width' => '1px', 'style' => 'solid', 'color' => '#d8dee9', 'side' => 'all', 'radius' => '8px' ],
                            'titleColor' => '#111827',
                            'titleAlign' => 'left',
                            'titleTypo' => [ 'fontSize' => [ 'desktop' => 22, 'tablet' => 20, 'mobile' => 18 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'titleMargin' => [ 'top' => '0px', 'right' => '0px', 'bottom' => '8px', 'left' => '0px' ],
                            'descriptionColor' => '#6b7280',
                            'descriptionAlign' => 'left',
                            'descriptionTypo' => [ 'fontSize' => [ 'desktop' => 15, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 400, 'lineHeight' => '145%' ],
                            'descriptionMargin' => [ 'top' => '0px', 'right' => '0px', 'bottom' => '24px', 'left' => '0px' ],
                            'successMsg' => 'Registration Confirmed! Your confirmation pass and access details have been emailed.',
                            'successMsgColor' => '#0f766e'
                        ],
                        'fields' => [
                            [
                                'id' => 'ev_sec1',
                                'type' => 'section',
                                'column' => 1,
                                'size' => 100,
                                'label' => '1. Attendee Contact Details',
                                'help' => 'Accurate information ensures badge printing and streaming credentials are correct.',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ev_name',
                                'type' => 'text',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Full Name',
                                'labelPosition' => 'column',
                                'placeholder' => 'Dr. Jane Doe',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ev_email',
                                'type' => 'email',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Work Email',
                                'labelPosition' => 'column',
                                'placeholder' => 'jane.doe@enterprise.org',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ev_company',
                                'type' => 'text',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Company / Institution',
                                'labelPosition' => 'column',
                                'placeholder' => 'Acme Technologies',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ev_title',
                                'type' => 'text',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Job Title',
                                'labelPosition' => 'column',
                                'placeholder' => 'Head of Engineering',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ev_phone',
                                'type' => 'phone',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Mobile Phone Number',
                                'labelPosition' => 'column',
                                'placeholder' => '+1 (555) 234-5678',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ev_sec2',
                                'type' => 'section',
                                'column' => 1,
                                'size' => 100,
                                'label' => '2. Attendance & Preferences',
                                'help' => 'Choose your format, workshop sessions, and on-site accommodations.',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ev_format',
                                'type' => 'radio',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Attendance Format',
                                'labelPosition' => 'column',
                                'isRequired' => true,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'In-Person Pass (Moscone Center, San Francisco)', 'value' => 'in_person' ],
                                    [ 'label' => 'Virtual Livestream & Interactive Q&A Pass', 'value' => 'virtual' ],
                                ],
                            ],
                            [
                                'id' => 'ev_tracks',
                                'type' => 'checkbox',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Key Tracks of Interest',
                                'labelPosition' => 'column',
                                'isRequired' => false,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'Agentic AI, LLM Orchestration & RAG', 'value' => 'ai_agents' ],
                                    [ 'label' => 'Cloud Native, Kubernetes & Edge Computing', 'value' => 'cloud_native' ],
                                    [ 'label' => 'Design Systems, Accessibility & Micro-Interactions', 'value' => 'design_ux' ],
                                    [ 'label' => 'Founder Keynotes, Venture Capital & Growth', 'value' => 'startup_growth' ],
                                ],
                            ],
                            [
                                'id' => 'ev_diet',
                                'type' => 'select',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Dietary Requirement (In-Person)',
                                'labelPosition' => 'column',
                                'placeholder' => 'Select dietary option',
                                'isRequired' => false,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'Standard / None', 'value' => 'none' ],
                                    [ 'label' => 'Vegetarian', 'value' => 'vegetarian' ],
                                    [ 'label' => 'Vegan', 'value' => 'vegan' ],
                                    [ 'label' => 'Gluten-Free', 'value' => 'gluten_free' ],
                                    [ 'label' => 'Halal', 'value' => 'halal' ],
                                    [ 'label' => 'Kosher', 'value' => 'kosher' ],
                                ],
                            ],
                            [
                                'id' => 'ev_date',
                                'type' => 'date',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Expected Arrival Date',
                                'labelPosition' => 'column',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ev_access',
                                'type' => 'toggle',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Do you require wheelchair accessibility or hearing assistance?',
                                'labelPosition' => 'column',
                                'onLabel' => 'Yes, accommodations required',
                                'offLabel' => 'No assistance needed',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                        ],
                        'labelS' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 15, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'color' => '#111827',
                        ],
                        'input' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 14, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 400, 'lineHeight' => '135%' ],
                            'color' => '#111827',
                            'padding' => [ 'top' => '11px', 'right' => '14px', 'bottom' => '11px', 'left' => '14px' ],
                            'border' => [ 'width' => '1px', 'style' => 'solid', 'color' => '#cbd5e1', 'side' => 'all', 'radius' => '6px' ],
                        ],
                        'radioCheckLabelColor' => '#374151',
                        'button' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 16, 'tablet' => 15, 'mobile' => 14 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'colors' => [ 'color' => '#ffffff', 'bg' => '#0f766e' ],
                            'padding' => [ 'top' => '14px', 'right' => '28px', 'bottom' => '14px', 'left' => '28px' ],
                        ],
                        'design' => [
                            'theme' => 'clean-professional',
                            'layout' => 'classic',
                            'inputStyle' => 'outlined',
                            'button' => [
                                'variant' => 'filled',
                                'label' => 'Complete Registration',
                                'width' => 'full',
                                'align' => 'left',
                                'radius' => '6px',
                                'hoverEffect' => 'none',
                                'transition' => 250,
                            ],
                            'card' => [ 'enable' => false ],
                            'progress' => [
                                'enable' => true,
                                'style' => 'gradient',
                                'position' => 'top',
                                'height' => '6px',
                                'gradient' => 'linear-gradient(135deg, #0f766e 0%, #14b8a6 100%)',
                                'showLabel' => true,
                            ],
                            'success' => [
                                'style' => 'card',
                                'icon' => 'check',
                                'animation' => 'fade',
                                'title' => 'Registration Confirmed!',
                                'duration' => 3000,
                            ],
                            'label' => [ 'requiredMark' => 'badge' ],
                        ],
                    ];

                case 'job-application':
                    return [
                        'cId' => 'svb-job-app',
                        'form' => [
                            'id' => 'svb-form-job-app',
                            'creator_id' => 1,
                            'title' => 'Senior Full-Stack Engineer Application',
                            'description' => 'We are seeking passionate product builders to help design and scale modern web applications.',
                            'bgColor' => '#ffffff',
                            'padding' => [ 'top' => '32px', 'right' => '32px', 'bottom' => '32px', 'left' => '32px' ],
                            'border' => [ 'width' => '1px', 'style' => 'solid', 'color' => '#e2e8f0', 'side' => 'all', 'radius' => '12px' ],
                            'titleColor' => '#0f172a',
                            'titleAlign' => 'left',
                            'titleTypo' => [ 'fontSize' => [ 'desktop' => 22, 'tablet' => 20, 'mobile' => 18 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'titleMargin' => [ 'top' => '0px', 'right' => '0px', 'bottom' => '8px', 'left' => '0px' ],
                            'descriptionColor' => '#64748b',
                            'descriptionAlign' => 'left',
                            'descriptionTypo' => [ 'fontSize' => [ 'desktop' => 15, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 400, 'lineHeight' => '145%' ],
                            'descriptionMargin' => [ 'top' => '0px', 'right' => '0px', 'bottom' => '24px', 'left' => '0px' ],
                            'successMsg' => 'Application Received! Our recruiting team reviews every candidate within 48 hours.',
                            'successMsgColor' => '#16a34a'
                        ],
                        'fields' => [
                            [
                                'id' => 'ja_name',
                                'type' => 'text',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Candidate Full Name',
                                'labelPosition' => 'column',
                                'placeholder' => 'e.g. Taylor Reed',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ja_email',
                                'type' => 'email',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Email Address',
                                'labelPosition' => 'column',
                                'placeholder' => 'taylor.reed@domain.com',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ja_phone',
                                'type' => 'phone',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Phone Number',
                                'labelPosition' => 'column',
                                'placeholder' => '+1 (555) 456-7890',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ja_url',
                                'type' => 'url',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'GitHub / Portfolio / LinkedIn URL',
                                'labelPosition' => 'column',
                                'placeholder' => 'https://github.com/username',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ja_stack',
                                'type' => 'select',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Primary Technical Focus',
                                'labelPosition' => 'column',
                                'placeholder' => 'Select primary tech stack',
                                'isRequired' => true,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'TypeScript / React / Node.js', 'value' => 'ts_react' ],
                                    [ 'label' => 'Python / FastAPI / Data Engineering', 'value' => 'python_fastapi' ],
                                    [ 'label' => 'Go / High-Throughput Microservices', 'value' => 'golang' ],
                                    [ 'label' => 'PHP 8 / Modern WordPress / Laravel', 'value' => 'php_wp' ],
                                ],
                            ],
                            [
                                'id' => 'ja_exp',
                                'type' => 'number',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Years of Relevant Experience',
                                'labelPosition' => 'column',
                                'placeholder' => '5',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ja_start',
                                'type' => 'date',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Target Start Date',
                                'labelPosition' => 'column',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ja_level',
                                'type' => 'opinion_scale',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Rate your self-assessed proficiency with Distributed Architecture & APIs',
                                'labelPosition' => 'column',
                                'help' => '1 = Fundamental, 10 = Principal / Architect Level',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ja_impact',
                                'type' => 'paragraph',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Briefly describe a high-impact technical project you led or built',
                                'labelPosition' => 'column',
                                'help' => 'Explain the problem, technical choices made, and quantifiable impact achieved',
                                'placeholder' => 'I engineered a real-time data streaming pipeline that...',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ja_auth',
                                'type' => 'radio',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Employment Authorization Status',
                                'labelPosition' => 'column',
                                'isRequired' => true,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'Authorized to work without sponsorship', 'value' => 'authorized' ],
                                    [ 'label' => 'Will require work visa sponsorship now', 'value' => 'need_sponsorship' ],
                                    [ 'label' => 'Will require visa renewal or sponsorship in future', 'value' => 'future_sponsorship' ],
                                ],
                            ],
                            [
                                'id' => 'ja_remote',
                                'type' => 'toggle',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Are you open to fully remote collaboration across global timezones?',
                                'labelPosition' => 'column',
                                'onLabel' => 'Open to 100% Remote',
                                'offLabel' => 'Prefers Hybrid / On-Site',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                        ],
                        'labelS' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 15, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'color' => '#0f172a',
                        ],
                        'input' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 14, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 400, 'lineHeight' => '135%' ],
                            'color' => '#0f172a',
                            'padding' => [ 'top' => '11px', 'right' => '14px', 'bottom' => '11px', 'left' => '14px' ],
                            'border' => [ 'width' => '1px', 'style' => 'solid', 'color' => '#e2e8f0', 'side' => 'all', 'radius' => '8px' ],
                        ],
                        'radioCheckLabelColor' => '#334155',
                        'button' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 16, 'tablet' => 15, 'mobile' => 14 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'colors' => [ 'color' => '#ffffff', 'bg' => '#2563eb' ],
                            'padding' => [ 'top' => '14px', 'right' => '28px', 'bottom' => '14px', 'left' => '28px' ],
                        ],
                        'design' => [
                            'theme' => 'modern-minimal',
                            'layout' => 'minimal',
                            'inputStyle' => 'outlined',
                            'button' => [
                                'variant' => 'filled',
                                'label' => 'Submit Application',
                                'width' => 'full',
                                'align' => 'left',
                                'radius' => '8px',
                                'hoverEffect' => 'none',
                                'transition' => 250,
                            ],
                            'card' => [ 'enable' => false ],
                            'progress' => [
                                'enable' => true,
                                'style' => 'gradient',
                                'position' => 'top',
                                'height' => '6px',
                                'gradient' => 'linear-gradient(135deg, #2563eb 0%, #6366f1 100%)',
                                'showLabel' => true,
                            ],
                            'success' => [
                                'style' => 'card',
                                'icon' => 'check',
                                'animation' => 'fade',
                                'title' => 'Application Received!',
                                'duration' => 3000,
                            ],
                            'label' => [ 'requiredMark' => 'badge' ],
                        ],
                    ];

                case 'bug-report':
                    return [
                        'cId' => 'svb-bug-report',
                        'form' => [
                            'id' => 'svb-form-bug-report',
                            'creator_id' => 1,
                            'title' => 'Bug Report & Issue Tracker',
                            'description' => 'Help our engineering team troubleshoot and resolve application or interface glitches quickly.',
                            'bgColor' => '#ffffff',
                            'padding' => [ 'top' => '32px', 'right' => '32px', 'bottom' => '32px', 'left' => '32px' ],
                            'border' => [ 'width' => '1px', 'style' => 'solid', 'color' => '#d8dee9', 'side' => 'all', 'radius' => '8px' ],
                            'titleColor' => '#111827',
                            'titleAlign' => 'left',
                            'titleTypo' => [ 'fontSize' => [ 'desktop' => 22, 'tablet' => 20, 'mobile' => 18 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'titleMargin' => [ 'top' => '0px', 'right' => '0px', 'bottom' => '8px', 'left' => '0px' ],
                            'descriptionColor' => '#6b7280',
                            'descriptionAlign' => 'left',
                            'descriptionTypo' => [ 'fontSize' => [ 'desktop' => 15, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 400, 'lineHeight' => '145%' ],
                            'descriptionMargin' => [ 'top' => '0px', 'right' => '0px', 'bottom' => '24px', 'left' => '0px' ],
                            'successMsg' => 'Issue Logged! A support ticket has been created and our team is investigating.',
                            'successMsgColor' => '#0f766e'
                        ],
                        'fields' => [
                            [
                                'id' => 'br_name',
                                'type' => 'text',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Your Name (Optional)',
                                'labelPosition' => 'column',
                                'placeholder' => 'Chris Evans',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'br_email',
                                'type' => 'email',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Notification Email',
                                'labelPosition' => 'column',
                                'placeholder' => 'chris@domain.com',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'br_url',
                                'type' => 'url',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'URL where the issue occurred',
                                'labelPosition' => 'column',
                                'placeholder' => 'https://example.com/checkout/step-2',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'br_category',
                                'type' => 'select',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Issue Category',
                                'labelPosition' => 'column',
                                'placeholder' => 'Select category',
                                'isRequired' => true,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'Visual / CSS Layout Glitch', 'value' => 'visual' ],
                                    [ 'label' => 'Broken Link, Button or Modal', 'value' => 'broken_ui' ],
                                    [ 'label' => 'Form Submission or API Error', 'value' => 'api_error' ],
                                    [ 'label' => 'Slow Performance / Freezing', 'value' => 'performance' ],
                                    [ 'label' => 'Security or Account Access', 'value' => 'security' ],
                                ],
                            ],
                            [
                                'id' => 'br_urgency',
                                'type' => 'radio',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Severity / Urgency',
                                'labelPosition' => 'column',
                                'isRequired' => true,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'Low (Cosmetic annoyance)', 'value' => 'low' ],
                                    [ 'label' => 'Medium (Workaround available)', 'value' => 'medium' ],
                                    [ 'label' => 'High (Feature unusable)', 'value' => 'high' ],
                                    [ 'label' => 'Critical Blocker (System down)', 'value' => 'critical' ],
                                ],
                            ],
                            [
                                'id' => 'br_date',
                                'type' => 'date',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Date & Time Issue Occurred',
                                'labelPosition' => 'column',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'br_steps',
                                'type' => 'paragraph',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Steps to Reproduce & Expected vs Actual Result',
                                'labelPosition' => 'column',
                                'help' => '1. Clicked X button, 2. Saw Y error instead of expected Z',
                                'placeholder' => '1. Navigated to...\n2. Clicked submit...\n3. Encountered error...',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'br_rating',
                                'type' => 'star_rating',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Rate your overall experience with application reliability',
                                'labelPosition' => 'column',
                                'help' => '1 = Frequently Broken, 5 = Highly Reliable & Rock Solid',
                                'isRequired' => false,
                                'isDisable' => false,
                                'maxStars' => 5,
                            ],
                        ],
                        'labelS' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 15, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'color' => '#111827',
                        ],
                        'input' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 14, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 400, 'lineHeight' => '135%' ],
                            'color' => '#111827',
                            'padding' => [ 'top' => '11px', 'right' => '14px', 'bottom' => '11px', 'left' => '14px' ],
                            'border' => [ 'width' => '1px', 'style' => 'solid', 'color' => '#cbd5e1', 'side' => 'all', 'radius' => '6px' ],
                        ],
                        'radioCheckLabelColor' => '#374151',
                        'button' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 16, 'tablet' => 15, 'mobile' => 14 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'colors' => [ 'color' => '#ffffff', 'bg' => '#dc2626' ],
                            'padding' => [ 'top' => '14px', 'right' => '28px', 'bottom' => '14px', 'left' => '28px' ],
                        ],
                        'design' => [
                            'theme' => 'clean-professional',
                            'layout' => 'classic',
                            'inputStyle' => 'outlined',
                            'button' => [
                                'variant' => 'filled',
                                'label' => 'Submit Bug Report',
                                'width' => 'full',
                                'align' => 'left',
                                'radius' => '6px',
                                'hoverEffect' => 'none',
                                'transition' => 250,
                            ],
                            'card' => [ 'enable' => false ],
                            'progress' => [ 'enable' => false ],
                            'success' => [
                                'style' => 'card',
                                'icon' => 'check',
                                'animation' => 'fade',
                                'title' => 'Report Submitted!',
                                'duration' => 3000,
                            ],
                            'label' => [ 'requiredMark' => 'badge' ],
                        ],
                    ];

                case 'employee-onboarding':
                    return [
                        'cId' => 'svb-onboarding',
                        'form' => [
                            'id' => 'svb-form-onboarding',
                            'creator_id' => 1,
                            'title' => '30-Day New Hire Onboarding Survey',
                            'description' => 'Welcome to the team! Share your feedback so People Ops can make your onboarding journey seamless.',
                            'bgColor' => '#f8fafc',
                            'padding' => [ 'top' => '30px', 'right' => '28px', 'bottom' => '30px', 'left' => '28px' ],
                            'border' => [ 'width' => '0px', 'style' => 'solid', 'color' => '#e9ecf5', 'side' => 'all', 'radius' => '18px' ],
                            'titleColor' => '#1e293b',
                            'titleAlign' => 'left',
                            'titleTypo' => [ 'fontSize' => [ 'desktop' => 22, 'tablet' => 20, 'mobile' => 18 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'titleMargin' => [ 'top' => '0px', 'right' => '0px', 'bottom' => '8px', 'left' => '0px' ],
                            'descriptionColor' => '#64748b',
                            'descriptionAlign' => 'left',
                            'descriptionTypo' => [ 'fontSize' => [ 'desktop' => 15, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 400, 'lineHeight' => '145%' ],
                            'descriptionMargin' => [ 'top' => '0px', 'right' => '0px', 'bottom' => '24px', 'left' => '0px' ],
                            'successMsg' => 'Thank you! Your feedback helps People Ops continuously elevate our team culture.',
                            'successMsgColor' => '#0f9d58'
                        ],
                        'fields' => [
                            [
                                'id' => 'ob_dept',
                                'type' => 'select',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Your Department',
                                'labelPosition' => 'column',
                                'placeholder' => 'Select department',
                                'isRequired' => true,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'Software Engineering', 'value' => 'engineering' ],
                                    [ 'label' => 'Product & Design', 'value' => 'product_design' ],
                                    [ 'label' => 'Sales & Business Development', 'value' => 'sales' ],
                                    [ 'label' => 'Customer Success & Support', 'value' => 'support' ],
                                    [ 'label' => 'People Ops & Operations', 'value' => 'people_ops' ],
                                ],
                            ],
                            [
                                'id' => 'ob_start',
                                'type' => 'date',
                                'column' => 1,
                                'size' => 50,
                                'label' => 'Your Start Date',
                                'labelPosition' => 'column',
                                'isRequired' => true,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ob_welcome_rating',
                                'type' => 'star_rating',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'How welcomed and supported did you feel during your first month?',
                                'labelPosition' => 'column',
                                'help' => 'Rate from 1 (Underwhelming) to 5 (Warm, proactive, and inclusive)',
                                'isRequired' => true,
                                'isDisable' => false,
                                'maxStars' => 5,
                            ],
                            [
                                'id' => 'ob_equipment',
                                'type' => 'toggle',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Did you receive all necessary hardware, tools, and credentials on Day 1?',
                                'labelPosition' => 'column',
                                'onLabel' => 'Fully equipped on Day 1',
                                'offLabel' => 'Encountered delays / missing access',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ob_goal_clarity',
                                'type' => 'opinion_scale',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Clarity of your 30-60-90 day expectations and team objectives',
                                'labelPosition' => 'column',
                                'help' => '1 = Unclear / vague, 10 = Crystal clear roadmap',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ob_mentorship',
                                'type' => 'radio',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'How would you evaluate your onboarding buddy or manager mentorship?',
                                'labelPosition' => 'column',
                                'isRequired' => true,
                                'isDisable' => false,
                                'options' => [
                                    [ 'label' => 'Exceptional: Proactive daily check-ins and clear guidance', 'value' => 'exceptional' ],
                                    [ 'label' => 'Helpful: Readily available whenever I had questions', 'value' => 'helpful' ],
                                    [ 'label' => 'Average: General support, but could be more structured', 'value' => 'average' ],
                                    [ 'label' => 'Needs Improvement: Struggled to find answers or guidance', 'value' => 'needs_improvement' ],
                                ],
                            ],
                            [
                                'id' => 'ob_feedback',
                                'type' => 'paragraph',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'What has been the highlight so far, and what can we improve?',
                                'labelPosition' => 'column',
                                'placeholder' => 'The onboarding sessions were great, but I think...',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                            [
                                'id' => 'ob_coffee',
                                'type' => 'toggle',
                                'column' => 1,
                                'size' => 100,
                                'label' => 'Would you like to schedule an informal 1-on-1 check-in with People Ops?',
                                'labelPosition' => 'column',
                                'onLabel' => 'Yes, let\'s grab virtual coffee!',
                                'offLabel' => 'No thanks, all good!',
                                'isRequired' => false,
                                'isDisable' => false,
                            ],
                        ],
                        'labelS' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 15, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'color' => '#1e293b',
                        ],
                        'input' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 14, 'tablet' => 14, 'mobile' => 14 ], 'fontWeight' => 400, 'lineHeight' => '135%' ],
                            'color' => '#1e293b',
                            'padding' => [ 'top' => '11px', 'right' => '14px', 'bottom' => '11px', 'left' => '14px' ],
                            'border' => [ 'width' => '1px', 'style' => 'solid', 'color' => '#e4e8f2', 'side' => 'all', 'radius' => '10px' ],
                        ],
                        'radioCheckLabelColor' => '#475569',
                        'button' => [
                            'typo' => [ 'fontSize' => [ 'desktop' => 16, 'tablet' => 15, 'mobile' => 14 ], 'fontWeight' => 600, 'lineHeight' => '135%' ],
                            'colors' => [ 'color' => '#ffffff', 'bg' => '#6366f1' ],
                            'padding' => [ 'top' => '14px', 'right' => '28px', 'bottom' => '14px', 'left' => '28px' ],
                        ],
                        'design' => [
                            'theme' => 'soft-card',
                            'layout' => 'card',
                            'inputStyle' => 'outlined',
                            'card' => [
                                'enable' => true,
                                'radius' => '14px',
                                'hoverEffect' => 'lift',
                            ],
                            'button' => [
                                'variant' => 'filled',
                                'label' => 'Submit Onboarding Check-In',
                                'width' => 'full',
                                'align' => 'left',
                                'radius' => '10px',
                                'hoverEffect' => 'lift',
                                'transition' => 250,
                            ],
                            'progress' => [
                                'enable' => true,
                                'style' => 'gradient',
                                'position' => 'top',
                                'height' => '6px',
                                'gradient' => 'linear-gradient(135deg, #6366f1 0%, #ec4899 100%)',
                                'showLabel' => true,
                            ],
                            'success' => [
                                'style' => 'card',
                                'icon' => 'check',
                                'animation' => 'fade',
                                'title' => 'Feedback Received!',
                                'duration' => 3000,
                            ],
                            'label' => [ 'requiredMark' => 'badge' ],
                        ],
                    ];

                default:
                    return [];
            }
        }
    }

    new BPSVB_Patterns();
}

